server:
  port: 8010

spring:
  application:
    name: spring-cloud-eureka-movie-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
